package team.gif;

import team.gif.commands.*;
import team.gif.autocommands.CanExtend;
import team.gif.autocommands.CanRetract;
import team.gif.autocommands.ElevSetpoint;
import team.gif.autocommands.QuickStack;
import team.gif.autocommands.Stacro;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * @author PatrickUbelhor
 * 
 * This class designates the ports for the joysticks and the location for each button.
 * Buttons can be programmed to run a command in the constructor.
 * DO NOT EDIT THIS FILE WITHOUT PERMISSION. PULL REQUESTS WILL BE REJECTED.
 */
public class OI {
    
	public static final Joystick leftStick = new Joystick(0);
	public static final Joystick rightStick = new Joystick(1);
	public static final Joystick auxStick = new Joystick(2);
	public static final Joystick leonardo = new Joystick(3);
	
	public static Button leftTrigger = new JoystickButton(leftStick, 1);
	private static Button left2;
	private static Button left3;
	private static Button left4;
	private static Button left5;
	
	private static Button rightTrigger;
	private static Button right2;
	private static Button right3;
	private static Button right4;
	private static Button right5;
	
	private static Button auxTrigger;
	private static Button aux2;
	private static Button aux3;
	private static Button aux4;
	private static Button aux5;
	private static Button aux6;
	private static Button aux7;
	private static Button aux8;
	private static Button aux9;
	private static Button aux10;
	private static Button aux11;
	
	private static Button leo3;
	private static Button leo4;
	
	public OI() {
		left2 = new JoystickButton(leftStick, 2);
		left3 = new JoystickButton(leftStick, 3);
		left4 = new JoystickButton(leftStick, 4);
		left5 = new JoystickButton(leftStick, 5);
		
		rightTrigger = new JoystickButton(rightStick, 1);
		right2 = new JoystickButton(rightStick, 2);
		right3 = new JoystickButton(rightStick, 3);
		right4 = new JoystickButton(rightStick, 4);
		right5 = new JoystickButton(rightStick, 5);
		
		auxTrigger = new JoystickButton(auxStick, 1);
		aux2 = new JoystickButton(auxStick, 2);
		aux3 = new JoystickButton(auxStick, 3);
		aux4 = new JoystickButton(auxStick, 4);
		aux5 = new JoystickButton(auxStick, 5);
		aux6 = new JoystickButton(auxStick, 6);
		aux7 = new JoystickButton(auxStick, 7);
		aux8 = new JoystickButton(auxStick, 8);
		aux9 = new JoystickButton(auxStick, 9);
		aux10 = new JoystickButton(auxStick, 10);
		aux11 = new JoystickButton(auxStick, 11);
		
		leo3 = new JoystickButton(leonardo, 3);
		leo4 = new JoystickButton(leonardo, 4);

		//left2.whenPressed(new fastriggerHard(1, 0.15));
		//left3.whenPressed(new fastriggerHard(-1, 0.4));
		left4.whenPressed(new CanRetract());
		left5.whenPressed(new CanExtend());
		
		rightTrigger.whenPressed(new CollectorOpen());
		rightTrigger.whenReleased(new CollectorClose());
		right2.whileHeld(new CollectorReceive());
		right3.whileHeld(new CollectorEject());
		right4.whileHeld(new CollectorRotate(false));
		right5.whileHeld(new CollectorRotate(true));
		
		auxTrigger.whenPressed(new ChopsticksClose());
		aux2.whenReleased(new ElevatorCoastDown());
		//aux3.whenReleased(new ElevatorCoastUp());
		aux4.whenPressed(new ChopsticksOpen());
		aux5.whenPressed(new Stacro());
		aux6.whileHeld(new QuickStack());
		aux7.whenPressed(new ElevSetpoint(Globals.kElevatorLevel2));
		aux8.whenPressed(new ElevSetpoint(Globals.kElevatorLevel3));
		aux9.whenPressed(new ElevSetpoint(Globals.kElevatorLevel4));
		aux10.whenPressed(new ElevSetpoint(Globals.kElevatorLevel5));
		aux11.toggleWhenPressed(new HolderOpen());
		
		//leo3.whenPressed(new ElevBumpDown());
		//leo4.whenPressed(new ElevBumpUp());
	}
	
}

